name: CI Pipeline  

on:
  push:  # Triggers on EVERY push to ANY branch 
    branches: [ '**' ]  

jobs:
  ci:  
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Matches Dockerfile

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # For tests

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest 



      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: Set image tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "IMAGE_TAG=prod-${GITHUB_SHA}" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "IMAGE_TAG=dev-${GITHUB_SHA}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Build from root
          push: true  # Actually push to registry
          tags: ${{ secrets.DOCKER_USERNAME }}/ci-pipeline-demo:${{ env.IMAGE_TAG }}
